spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: testdb
    password: testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.batch.item.database: DEBUG
